version: '3'
services:
  presto:
    hostname: presto
    image: 'starburstdata/presto:0.203-e.0.1'
    container_name: presto
    ports:
      - '8080:8080'
    volumes: 
      - './presto/minio.properties:/usr/lib/presto/etc/catalog/minio.properties'
      - './hadoop/lib/json-serde-1.3.8-jar-with-dependencies.jar:/usr/lib/presto/lib/plugin/hive-hadoop2/json-serde-1.3.8-jar-with-dependencies.jar'
  hadoop:
    hostname: hadoop-master
    image: 'prestodb/cdh5.13-hive:latest'
    container_name: hadoop-master
    volumes:
      - './hadoop/core-site.xml:/etc/hadoop/conf/core-site.xml'
      - './hadoop/lib/json-udf-1.3.8-jar-with-dependencies.jar:/usr/lib/hive/lib/json-udf-1.3.8-jar-with-dependencies.jar'
      - './hadoop/lib/json-serde-1.3.8-jar-with-dependencies.jar:/usr/lib/hive/lib/json-serde-1.3.8-jar-with-dependencies.jar'
  minio:
    hostname: minio
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
    volumes:
      - './minio/data/:/data'
      - './minio/config:/root/.minio'
    environment:
      MINIO_ACCESS_KEY: V42FCGRVMK24JJ8DHUYG
      MINIO_SECRET_KEY: bKhWxVF3kQoLY9kFmt91l+tDrEoZjqnWXzY9Eza
    command: server /data